apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blog-app-secrets
  namespace: blog-app-ns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: blog-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: production/blog-app