name: Security Workflow

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    


jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Download Trivy HTML Template
        run: wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Trivy File System Scan (Generate Report)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,misconfig'
          format: 'template'
          template: '@html.tpl'
          output: 'trivy-report.html'
          exit-code: '0'
      
      - name: Trivy Security Gate (Fail on Critical/High)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,misconfig'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Security-Report
          path: trivy-report.html
          retention-days: 7

  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        env:
          BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          HEAD_SHA: ${{ github.sha }}
        with:
          path: ./
          base: ${{ env.BASE_SHA }}
          head: ${{ env.HEAD_SHA }}
          extra_args: --only-verified

  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=blog-app
            -Dsonar.sources=.
            -Dsonar.exclusions=**/tests/**,**/test_*.py